# -*- coding: utf-8 -*-
"""Webscrapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zTsWuNl3-405_ai4X7dpPe3GFNIXRrRP
"""

# Loading required libraries

import numpy as np
import pandas as pd

import requests
from bs4 import BeautifulSoup

# Identify the URL

URL ="https://codegnan.com/"

# Loading the Webpage  in memory using requests library

page = requests.get(URL)

#  Check the Status Code of the page

page.status_code

# Extracting the HTML Code of the webpage

htmlcode = page.text
soup = BeautifulSoup(htmlcode)

htmlcode

content = soup.find('div', attrs={'class':'page-content'})
text = content.text.split('\n')
print(text)

data=text[text.index('⭐ Our certification  programs ')+2:text.index('Companies where  Our students got placed ')-1]
vb=[i.strip() for i in data if i!='']
munvar=[i for i in vb if i!='']
print(munvar)

duration=[]
course=[]
description=[]
location=[]
for i in range(0,len(munvar),4):
    duration.append(munvar[i])
    course.append(munvar[i+1])
    description.append(munvar[i+2])
    location.append(munvar[i+3])

df=pd.DataFrame({'Duration':duration,'Course':course,'Description':description,'Location':location})

df

df.to_csv('certification.csv',index=False)

from google.colab import files
files.download('certification.csv')